Repository DhanushNehru/breakout-game, pull requests merged in 2022-10, with the labels that each got.

#34 Added
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest

#35 Add block lives
  script.js
Labels: enhancement, hacktoberfest

#38 Added git commands for beginners
  Contribution.md
Labels: documentation

#40 Making minor changes to HTMl for validation. Making some changes to C…
  index.html
  script.js
  styles.css
  utils/utilsColor.js
Labels: enhancement, hacktoberfest

#41 Resolve #39 - Redo of the design
  index.html
  styles.css
Labels: hacktoberfest
